name: Deb to IPA (No Signing)

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to .deb file"
        required: true
      ipa:
        description: "Direct URL to decrypted .ipa file"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download .deb and .ipa files
        run: |
          curl -L -o ${{ github.workspace }}/app.deb "${{ github.event.inputs.deb }}"
          curl -L -o ${{ github.workspace }}/app.ipa "${{ github.event.inputs.ipa }}"

      - name: Extract .deb contents
        run: dpkg-deb -X ${{ github.workspace }}/app.deb ${{ github.workspace }}/deb

      - name: Extract .ipa contents
        run: unzip -q ${{ github.workspace }}/app.ipa -d ${{ github.workspace }}/ipa

      - name: Copy tweak files into IPA app bundle
        run: |
          APP_DIR=$(find ${{ github.workspace }}/ipa/Payload -name '*.app' -type d | head -n1)
          echo "App directory: $APP_DIR"
          cp ${{ github.workspace }}/deb/var/jb/Library/MobileSubstrate/DynamicLibraries/*.dylib "$APP_DIR/"
          cp ${{ github.workspace }}/deb/var/jb/Library/MobileSubstrate/DynamicLibraries/*.plist "$APP_DIR/"

      - name: Repack IPA
        run: |
          cd ${{ github.workspace }}/ipa
          zip -qr ${{ github.workspace }}/patched.ipa Payload

      - name: Upload patched IPA
        uses: actions/upload-artifact@v4
        with:
          name: patched-ipa
          path: ${{ github.workspace }}/patched.ipa
