name: Deb to IPA and Upload to Catbox

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to .deb file"
        required: true
      ipa:
        description: "Direct URL to decrypted .ipa file"
        required: true
      github_token:
        description: "GitHub Token for release (default: ${{ secrets.GITHUB_TOKEN }})"
        required: false
        default: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download .deb and .ipa files
        run: |
          curl -L -o ${{ github.workspace }}/app.deb "${{ github.event.inputs.deb }}"
          curl -L -o ${{ github.workspace }}/app.ipa "${{ github.event.inputs.ipa }}"

      - name: Extract .deb contents
        run: dpkg-deb -X ${{ github.workspace }}/app.deb ${{ github.workspace }}/deb

      - name: Extract .ipa contents
        run: unzip -q ${{ github.workspace }}/app.ipa -d ${{ github.workspace }}/ipa

      - name: Copy tweak files into IPA app bundle
        run: |
          APP_DIR=$(find ${{ github.workspace }}/ipa/Payload -name '*.app' -type d | head -n1)
          echo "App directory: $APP_DIR"
          cp ${{ github.workspace }}/deb/var/jb/Library/MobileSubstrate/DynamicLibraries/*.dylib "$APP_DIR/"
          cp ${{ github.workspace }}/deb/var/jb/Library/MobileSubstrate/DynamicLibraries/*.plist "$APP_DIR/"

      - name: Repack IPA
        run: |
          cd ${{ github.workspace }}/ipa
          zip -qr ${{ github.workspace }}/patched.ipa Payload

      - name: Upload patched IPA to catbox.moe
        id: upload_catbox
        run: |
          response=$(curl -F "reqtype=fileupload" -F "fileToUpload=@${{ github.workspace }}/patched.ipa" https://catbox.moe/user/api.php)
          echo "Uploaded file URL: $response"
          # Extract the unique identifier (filename or path after last /)
          filename=$(basename "$response")
          echo "filename=$filename" >> $GITHUB_OUTPUT

      - name: Create GitHub release with catbox identifier in body
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "patched-ipa-$(date +'%Y%m%d%H%M%S')"
          name: "Patched IPA uploaded to catbox"
          body: |
            Uploaded patched IPA to catbox.moe with identifier:

            ${{ steps.upload_catbox.outputs.filename }}
        env:
          GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
