name: Deb to IPA and Release

on:
  workflow_dispatch:
    inputs:
      deb:
        description: "Direct URL to .deb file"
        required: true
      ipa:
        description: "Direct URL to decrypted .ipa file"
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download .deb and .ipa
        run: |
          curl -L -o app.deb "${{ github.event.inputs.deb }}"
          curl -L -o app.ipa "${{ github.event.inputs.ipa }}"

      - name: Extract tweak (.deb)
        run: dpkg-deb -X app.deb deb

      - name: Extract app (.ipa)
        run: unzip -q app.ipa -d ipa

      - name: Inject tweak into IPA
        run: |
          APP_DIR=$(find ipa/Payload -name '*.app' -type d | head -n1)
          cp deb/var/jb/Library/MobileSubstrate/DynamicLibraries/*.dylib "$APP_DIR/"
          cp deb/var/jb/Library/MobileSubstrate/DynamicLibraries/*.plist "$APP_DIR/"

      - name: Repack patched IPA
        run: |
          cd ipa
          zip -qr patched.ipa Payload
          cd ..

      - name: Generate timestamped tag
        id: tag
        run: echo "TAG=patched-ipa-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Release and Upload IPA
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG }}
          name: ipa
          body: |
            This release contains the patched IPA with injected tweak.
          assets: ipa/patched.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
